[package]
name = "tic-tac-toe-rust"
version = "0.1.0"
authors = ["Francis Gulotta <wizard@roborooter.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "1.5.5"
